import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/header";
import NewsletterSection from "@/components/common/newsLetter";
import Footer from "@/components/common/footer";
import { SessionProvider as NextAuthSessionProvider } from "next-auth/react";
import { SessionProvider } from "@/lib/contexts/session-context";
import { Toaster } from "sonner";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Spartan:wght@400;500;600;700&display=swap"
        />
      </head>
     
      <body >
      <NextAuthSessionProvider>
          <SessionProvider>
        <Header/>
        {children}
        <NewsletterSection/>
        <Footer/>
        </SessionProvider>
        </NextAuthSessionProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
